### ISSUE TITLE
[BUG] Incomplete repo data 

### ISSUE THREAD

**Issue by aonsyed** [redis/redis-debian#17]
**Describe the bug**

Repo is missing Origin, Lable, Suite, Version and Description

**To reproduce**

Here are the first few lines of the repo aka metadata 

```
curl -s https://packages.redis.io/deb/dists/jammy/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Codename: jammy
Date: Sun, 08 Oct 2023 08:18:57 UTC
Architectures: amd64 all i386 armhf arm64
Components: main
Suite:
```

**Expected behavior**

Here is what a standard repo should have 

```
curl -s https://ppa.launchpadcontent.net/redislabs/redis/ubuntu/dists/jammy/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Origin: LP-PPA-redislabs-redis
Label: Redis
Suite: jammy
Version: 22.04
Codename: jammy
Date: Wed, 06 Sep 2023 23:45:50 UTC
Architectures: amd64 arm64 armhf i386 ppc64el riscv64 s390x
Components: main
Description: Ubuntu Jammy 22.04
```

**Additional information**

Please make sure that the additional info is provided, it helps with tagging and pipelining upgrades, same applies for Release in addition to InRelease

**Comment by yossigo** [comment]
@aonsyed These are optional fields that are not mandatory. Launchpad uses them in certain way, but that doesn't mean any repository have to follow these conventions. Can you please provide more information about how this breaks pipelines?

**Comment by aonsyed** [comment]
Label suite version and origin make it much easier to identify those details. Right now the only identifying information is that the site is packages.redis.io with the correct gpg key, however since most of the OSS software uses third-party mirrors, these additional fields make it easier to detect those irrespective of the URL and most of upgrade mechanism like unattended-upgrades 

Here is a chunk of 50unattended-upgrades on debian based OSes 

````
Unattended-Upgrade::Origins-Pattern {
        // Codename based matching:
        // This will follow the migration of a release through different
        // archives (e.g. from testing to stable and later oldstable).
        // Software will be the latest available for the named release,
        // but the Debian release itself will not be automatically upgraded.
//      "origin=Debian,codename=${distro_codename}-updates";
//      "origin=Debian,codename=${distro_codename}-proposed-updates";
        "origin=Debian,codename=${distro_codename},label=Debian";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
    
 ```
As you can see most of it is based on the missing parameters, so anyone using unattended-upgrades would have to change the pattern values to include the site info specifically and that would only work till Redis repo is starts being mirrored by others. 

Additionally any other DevOps related work that uses data from InRelease to read the repo meta data for info and then do anything with the packages present like updates or version pinning or anything else would need extra steps to recognize the data from the URL instead of additional fields that are present for almost every other debian-based repo

**Comment by yossigo** [comment]
@aonsyed We'll use `packages.redis.io` as Origin and change Suite to match Codename. Unfortunately, the `deb-s3` tool we use doesn't seem to support adding a Label field, I hope those two are sufficient though.

**Comment by yossigo** [comment]
This was fixed with the latest package upload:

```
$ curl -s https://packages.redis.io/deb/dists/jammy/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: packages.redis.io
Codename: jammy
Date: Wed, 01 Nov 2023 13:51:04 UTC
Architectures: amd64 all i386 armhf arm64
Components: main
Suite: jammy
```

**Comment by janez33** [comment]
Hello, I'm still having this problem - doesn anyone know how to fix it this issue? :) Thank you in advance :)

![slika](https://github.com/redis/redis-debian/assets/4009092/1008d1c8-808a-4335-8210-3c70c0088271)

**Comment by yossigo** [comment]
@janez33 According to the docs you may need to run `apt-get --allow-releaseinfo-change update` to work around this change, you may want to try that.

**Comment by janez33** [comment]
@yossigo thank you so much :) it fixed the issue :) I was also reading man page for apt-secure but couldnt figure it out from this text
![slika](https://github.com/redis/redis-debian/assets/4009092/9e62101d-1683-4dd7-bc34-308b397568b4)

that this is the solution for this problem:
![slika](https://github.com/redis/redis-debian/assets/4009092/2c5d69e9-3232-44f5-959e-96dacddfe54c)
